### ISSUE TITLE
HIDPI Daemon notification permanently displayed

### ISSUE THREAD

**Issue by ArtificialAmateur** [pop-os/hidpi-daemon#20] opened 2019-01-31 18:20 UTC
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="18.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.10"
VERSION_ID="18.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic
```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
hidpi-daemon:
  Installed: 18.04.4~1533160664~18.10~85d4567
  Candidate: 18.04.4~1533160664~18.10~85d4567
  Version table:
 *** 18.04.4~1533160664~18.10~85d4567 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu cosmic/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu cosmic/main i386 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
Pop-OS! is installed on a laptop with an embedded 4k display causing the HIDPI notification to permanently be in place and is quite annoying, it would be more user friendly to have the option to opt-out and remove said notification.

**Steps to reproduce (if you know):**
1. Buy a Thinkpad X1E
2. Install Pop_OS!
3. Be annoyed at the permanent notification for the display that can't be removed.

**Expected behavior:**
I understand its purpose and it's really a great feature, but I just want to opt-out of seeing that notification 100% of the time.

**Other Notes:**
I also have GS Connect so every time I log in to my desktop that notification gets sent to my mobile devices as well.

**Comment by hongshaojichi** [comment] 2019-04-22 21:45
Yep. Seeing the exact same issue.

**Comment by RicardoEPRodrigues** [comment] 2019-04-25 20:16
I still have this issue in 19.04.

**Comment by brs17** [comment] 2019-04-26 14:05
You can disable the HiDPI daemon in Gnome Control Center under the `Devices`->`Displays`. This should remove the notification.

**Comment by RicardoEPRodrigues** [comment] 2019-04-26 14:24
Yes, but I want the Daemon enabled, but the notification to be removable... I don't want to always have it present.

**Comment by thomasholland123** [comment] 2019-09-23 06:53
Just wondered if any progress as happens on my MacBook Pro as well. 

Also, when I change to the LowDPI option, it gets replaced with another persistent notification.

**Comment by farazfazli** [comment] 2019-10-22 13:26
I am experiencing the same bug on my ThinkPad W541, running the latest OS version 19.10

Besides this small bug, the OS has been running extremely well overall and I'm impressed by the performance. Any help in dismissing this dialog would be much appreciated.

Thank you.

**Comment by cassidyjames** [comment] 2019-10-22 17:55
As a note, this is not strictly a bug, it's by design. Since GNOME does not have a concept of persistent notifications (i.e. like Android), the Daemon recreates the notification to ensure it's always present. A better design for the Daemon would be to integrate it into the system menu instead of abusing notifications for a persistent UI.

**Comment by thomasholland123** [comment] 2019-10-23 06:46
@cassidyjames 
Feel like this should still be a one time notification (to let the user know what it is and does) but it should point it towards the system menu like you said. 


Also: if it is a notification, is it possible to block it and still keep HiDPI?

**Comment by rdsngit** [comment] 2020-06-14 23:02
Same problem running Pop 20.04 on ThinkPad X1 Carbon (6), so annoying to have to notification every time you turn on the machine. Would be ideal to just have it as a setting without showing the notification.

**Comment by farazfazli** [comment] 2020-06-15 00:50
Is it possible to simply remove this notification/indication all together? There can be a simple switch in the settings to enable and disable HIDPI if a user chooses to do so. I can't see this being disabled very much by users anyway (most software works fine with HIDPI). If a user is having issues, they can disable it in the settings -or- have some type of method which detects that they are having an issue and prompts them (through a notification) to disable HIDPI mode.

**Comment by mboudreau** [comment] 2020-07-28 04:00
Why isn't the HiDPI Daemon not part of the notifications list in the settings?  That way you could disable it outright.

**Comment by ivopauly** [comment] 2021-01-17 13:56
I still have this issue in 20.04, using Dell Precision 5510 4K UHD.

**Comment by brycefranzen** [comment] 2021-11-16 14:54
I have the same issue. I'd love to be able to disable the notification all-together, but keep the daemon running.

**Comment by protodrew** [comment] 2021-12-24 05:51
bumping this because I am having the same issue still

**Comment by vorpalhex** [comment] 2021-12-30 17:49
Same here on an XPS 15 on 21.10.

**Comment by sommerper** [comment] 2022-02-03 17:23
Have the same problem on 2015 MacBook Pro

**Comment by BohdanK911** [comment] 2022-02-20 11:07
Same issue. 21.10, Lenovo Yoga 920

**Comment by bandrefilipe** [comment] 2022-03-23 12:55
Issue still persists. 20.10, Dell XPS 13

**Comment by eotfofiw** [comment] 2022-05-13 19:19
Is there any update on this? It's pretty irritating. "Turn off the daemon" isn't a fix, when the primary reason for me using Pop!_OS is how well it handled a hidpi laptop with a lodpi external display. I understand the initial notification, people may want to know what is happening. But I close it. It immediately comes back. I don't need to continuously know.

**Comment by hholst80** [comment] 2022-07-26 20:40
Same issue on fresh install. 
```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```
[Screencast from 07-26-2022 10:38:41 PM.webm](https://user-images.githubusercontent.com/6200749/181107816-817a1954-5d74-49d7-9ef9-7f3818215c11.webm)

**Comment by hholst80** [comment] 2022-07-26 20:44
> Edit:
> I realised I've just come on here and started moaning. You guys are making something great here. I absolutely love the distribution and all the effort you've gone through to make it as great as it is, is very much appreciated.

IMHO I do not consider it "moaning" if the issue is 4 years old PopOS! will seem to be lacking sufficient maintenance on essential usability issues. That is typically a no-recommend flag on my side. Why would I recommend anyone to use PopOS! over Ubuntu if the only things added on top of Ubuntu is not sufficiently maintained to be trusted?

**Comment by AndASM** [comment] 2023-02-17 00:08
If it's by design, should we notify the team every time it is intrusive? If that sounds unacceptable, maybe it's a design **flaw**.

**Comment by agingorange** [comment] 2023-06-15 09:11
Same here on a Dell XPS 1720 9720.

**Comment by zobbo** [comment] 2023-08-10 14:23
Same here on Thinkpad X1 Carbon 7 Gen

**Comment by kennebel** [comment] 2024-10-08 21:40
Piling in here with a new install of 22.04 on a Surface Laptop. Get the permanent notification. I'm guessing this will not be a thing with Cosmic.

**Comment by leviport** [comment] 2024-10-14 18:10
Correct, the HiDPI Daemon will not be ported to COSMIC DE.

**Comment by helios2k6** [comment] 2024-12-11 23:08
Yeah, this is still an issue right now. And it's extremely irritating.

**Comment by leviport** [comment] 2024-12-11 23:20
Just turn it off. It doesn't do much anyway.

**Closed by leviport** 2024-12-11 23:20 UTC
